#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

for cmd in shellcheck shfmt; do
    command -v "$cmd" >/dev/null 2>&1 ||
        {
            echo "Error: $cmd is missing"
            exit 1
        }
done

shopt -s extglob
shellcheck .bashrc scripts/!(*.ps1)
shfmt -d .bashrc scripts/!(*.ps1)
