name: Lint

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  shell:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - run: sudo apt-get update && sudo apt-get install -y shellcheck shfmt
      - run: |
          files=".bashrc .bash_profile .profile $(shfmt -f .)"
          shellcheck -e SC1091 $files
          shfmt -d $files
